//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KruegerQuotesEntities : DbContext
    {
        public KruegerQuotesEntities()
            : base("name=KruegerQuotesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryTerm> DeliveryTerms { get; set; }
        public virtual DbSet<Footer> Footers { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<QuoteHdr> QuoteHdrs { get; set; }
        public virtual DbSet<QuoteLine> QuoteLines { get; set; }
        public virtual DbSet<QuoteLineDefault> QuoteLineDefaults { get; set; }
        public virtual DbSet<QuoteRef> QuoteRefs { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Trailer> Trailers { get; set; }
        public virtual DbSet<TrailerDefault> TrailerDefaults { get; set; }
        public virtual DbSet<TrailerOption> TrailerOptions { get; set; }
        public virtual DbSet<TrailerQuestion> TrailerQuestions { get; set; }
        public virtual DbSet<TrailerQuestionAnswer> TrailerQuestionAnswers { get; set; }
        public virtual DbSet<Transportation> Transportations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
        public virtual DbSet<ReportTable> ReportTables { get; set; }
        public virtual DbSet<Wage> Wages { get; set; }
        public virtual DbSet<zzz> zzzs { get; set; }
        public virtual DbSet<zzzTrailerOption> zzzTrailerOptions { get; set; }
    }
}
