//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuoteHdr()
        {
            this.QuoteLines = new HashSet<QuoteLine>();
            this.QuoteLineDefaults = new HashSet<QuoteLineDefault>();
        }
    
        public int QuoteID { get; set; }
        public string QuoteRef { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public int CompanyID { get; set; }
        public int CustomerID { get; set; }
        public int TrailerID { get; set; }
        public string ItemNo { get; set; }
        public string ItemDescriptionShort { get; set; }
        public string ItemDescriptionLong { get; set; }
        public string ItemSalesDescription { get; set; }
        public string DrawingNo { get; set; }
        public Nullable<double> Hours { get; set; }
        public int TareWeight { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public decimal SellPrice { get; set; }
        public Nullable<decimal> CostMaterial { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<long> AllowReprint { get; set; }
        public Nullable<int> DeliveryTermId { get; set; }
        public string QuoteFile { get; set; }
        public string SpecialRequirement { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal SpecReqSellPrice { get; set; }
        public decimal SpecReqSellCost { get; set; }
        public string CostedBy { get; set; }
        public string Timestamp { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> TransportationId { get; set; }
        public string WarrantyPeriod { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CubicCapacity { get; set; }
        public int QuoteRefId { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<bool> ShowRequirementOnQuote { get; set; }
        public string SpecialRequirementB { get; set; }
        public decimal SpecReqSellPriceB { get; set; }
        public decimal SpecReqSellCostB { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DeliveryTerm DeliveryTerm { get; set; }
        public virtual Trailer Trailer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteLine> QuoteLines { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual Transportation Transportation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteLineDefault> QuoteLineDefaults { get; set; }
    }
}
