//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteRef
    {
        public int QuoteRefId { get; set; }
        public string QuoteRef1 { get; set; }
        public System.DateTime DateQuoted { get; set; }
    }
}
