//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.QuoteHdrs = new HashSet<QuoteHdr>();
        }
    
        public int RegistrationID { get; set; }
        public string RegistrationDescription { get; set; }
        public Nullable<decimal> RegoFee { get; set; }
        public Nullable<decimal> PlateFee { get; set; }
        public Nullable<bool> isDefault { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<decimal> AdminFee { get; set; }
        public Nullable<decimal> ProcessingFee { get; set; }
        public Nullable<decimal> StampDuty { get; set; }
        public string TrailerType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteHdr> QuoteHdrs { get; set; }
    }
}
