//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrailerOption
    {
        public int OptionID { get; set; }
        public string OptionDescription { get; set; }
        public string OptionDescriptionExtended { get; set; }
        public int CatID { get; set; }
        public string UoM { get; set; }
        public int UnitsPerTrailer { get; set; }
        public Nullable<int> TareWeightOption { get; set; }
        public string DrawingNo { get; set; }
        public string PartNo { get; set; }
        public Nullable<double> Hours { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> CostMaterial { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> AllowDiscount { get; set; }
        public Nullable<int> Margin { get; set; }
        public Nullable<decimal> PriceBookPrice { get; set; }
        public Nullable<int> CubicCapacityOption { get; set; }
        public Nullable<int> MaximumUnits { get; set; }
        public Nullable<int> UnitMultiplier { get; set; }
        public bool PrintQuantityOnQuote { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
