//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trailer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trailer()
        {
            this.QuoteHdrs = new HashSet<QuoteHdr>();
            this.TrailerDefaults = new HashSet<TrailerDefault>();
            this.TrailerDefaults1 = new HashSet<TrailerDefault>();
            this.TrailerDefaults2 = new HashSet<TrailerDefault>();
        }
    
        public int TrailerID { get; set; }
        public string ItemNo { get; set; }
        public string ItemDescriptionShort { get; set; }
        public string ItemDescriptionLong { get; set; }
        public string ItemSalesDescription { get; set; }
        public string DrawingNo { get; set; }
        public Nullable<double> Hours { get; set; }
        public int TareWeight { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public decimal SellPrice { get; set; }
        public Nullable<decimal> CostMaterial { get; set; }
        public Nullable<bool> Active { get; set; }
        public int SortOrder { get; set; }
        public decimal MaxDiscount { get; set; }
        public Nullable<int> Margin { get; set; }
        public string WarrantyPeriod { get; set; }
        public Nullable<int> CubicCapacity { get; set; }
        public string TrailerType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteHdr> QuoteHdrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrailerDefault> TrailerDefaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrailerDefault> TrailerDefaults1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrailerDefault> TrailerDefaults2 { get; set; }
    }
}
