//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrailerDefault
    {
        public int TrailerID { get; set; }
        public int CatID { get; set; }
        public int OptionID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Trailer Trailer { get; set; }
        public virtual Trailer Trailer1 { get; set; }
        public virtual Trailer Trailer2 { get; set; }
    }
}
