//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzz
    {
        public int OptionID { get; set; }
        public string OptionDescription { get; set; }
        public string OptionDescriptionExtended { get; set; }
        public int UnitsPerTrailer { get; set; }
        public Nullable<int> TareWeightOption { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> CostMaterial { get; set; }
        public Nullable<decimal> PriceBookPrice { get; set; }
        public Nullable<int> MaximumUnits { get; set; }
        public Nullable<int> UnitMultiplier { get; set; }
    }
}
